### ISSUE TITLE
p315 Unable to open model in Moveit Setup Assistant

### ISSUE THREAD

**Issue by threent2** [PacktPublishing/Mastering-ROS-2#12]
I have tried both to Create or to Edit but the file panda_description/urdf/panda.urdf.xacro can not be opened. See screenshots below.

<img width="428" height="169" alt="Image" src="https://github.com/user-attachments/assets/692c63af-d04c-4454-be80-df8ef3d99026" />

<img width="1118" height="786" alt="Image" src="https://github.com/user-attachments/assets/326aed51-8c1c-4fde-9126-b1e548ebb63b" />

Still the same error if I use the directory listed in the text.

**Comment by threent2** [comment]
I have just installed some Ubuntu upgrades (including a new kernel. When I click "Create ....
I now get to select the panda.urdf.xacro abd can click "Load Files". Progress gets to 70% and then aborts. Terminal output below
brian@HP-laptop:/master_ros2_ws$ ros2 launch moveit_setup_assistant setup_assistant.launch.py 
[INFO] [launch]: All log files can be found below /home/brian/.ros/log/2025-10-01-16-35-17-893252-HP-laptop-12794
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [moveit_setup_assistant-1]: process started with pid [12797]
[moveit_setup_assistant-1] [INFO] [1759332932.772749463] [moveit_setup_assistant.urdf]: Loaded panda robot model.
[moveit_setup_assistant-1] [INFO] [1759332932.792149129] [moveit_1416145157.moveit.core.robot_model]: Loading robot model 'panda'...
[moveit_setup_assistant-1] [INFO] [1759332932.792214546] [moveit_1416145157.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[moveit_setup_assistant-1] [INFO] [1759332983.229293842] [moveit_setup_assistant.urdf]: Loaded panda robot model.
[moveit_setup_assistant-1] [INFO] [1759332983.229372027] [moveit_1416145157.moveit.core.robot_model]: Loading robot model 'panda'...
[moveit_setup_assistant-1] [INFO] [1759332983.229401158] [moveit_1416145157.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[moveit_setup_assistant-1] [INFO] [1759332983.414301032] [moveit_1416145157.moveit.ros.rdf_loader]: Loaded robot model in 0.00286059 seconds
[moveit_setup_assistant-1] [INFO] [1759332983.414388778] [moveit_1416145157.moveit.core.robot_model]: Loading robot model 'panda'...
[moveit_setup_assistant-1] [INFO] [1759332983.414408909] [moveit_1416145157.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[moveit_setup_assistant-1] [INFO] [1759332984.694231196] [moveit_1416145157.moveit.ros.rdf_loader]: Loaded robot model in 0.00236715 seconds
[moveit_setup_assistant-1] [INFO] [1759332984.694313557] [moveit_1416145157.moveit.core.robot_model]: Loading robot model 'panda'...
[moveit_setup_assistant-1] [INFO] [1759332984.694331462] [moveit_1416145157.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[moveit_setup_assistant-1] Stack trace (most recent call last):
[moveit_setup_assistant-1] #31   Object "/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0", at 0x7b83b5b73736, in 
[moveit_setup_assistant-1] #30   Object "/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0", at 0x7b83b5b145c4, in 
[moveit_setup_assistant-1] #29   Object "/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5.15.13", at 0x7b83a4491d05, in 
[moveit_setup_assistant-1] #28   Object "/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.15.13", at 0x7b83b7517bfb, in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)
[moveit_setup_assistant-1] #27   Object "/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.15.13", at 0x7b83b7545a3a, in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)
[moveit_setup_assistant-1] #26   Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b70d8117, in QCoreApplication::notifyInternal2(QObject*, QEvent*)
[moveit_setup_assistant-1] #25   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7d6bd44, in QApplicationPrivate::notify_helper(QObject*, QEvent*)
[moveit_setup_assistant-1] #24   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7dcdfbe, in 
[moveit_setup_assistant-1] #23   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7dcaa38, in 
[moveit_setup_assistant-1] #22   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7d72873, in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool)
[moveit_setup_assistant-1] #21   Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b70d8117, in QCoreApplication::notifyInternal2(QObject*, QEvent*)
[moveit_setup_assistant-1] #20   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7d746af, in QApplication::notify(QObject*, QEvent*)
[moveit_setup_assistant-1] #19   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7d6bd44, in QApplicationPrivate::notify_helper(QObject*, QEvent*)
[moveit_setup_assistant-1] #18   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7db0df7, in QWidget::event(QEvent*)
[moveit_setup_assistant-1] #17   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7e697b7, in QAbstractButton::mouseReleaseEvent(QMouseEvent*)
[moveit_setup_assistant-1] #16   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7e695af, in 
[moveit_setup_assistant-1] #15   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7e6796e, in 
[moveit_setup_assistant-1] #14   Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7e676e3, in QAbstractButton::clicked(bool)
[moveit_setup_assistant-1] #13   Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b7112dbe, in 
[moveit_setup_assistant-1] #12   Object "/opt/ros/jazzy/lib/libmoveit_setup_core_plugins.so", at 0x7b839c5075c1, in moveit_setup::core::StartScreenWidget::loadFilesClick()
[moveit_setup_assistant-1] #11   Object "/opt/ros/jazzy/lib/libmoveit_setup_core_plugins.so", at 0x7b839c507249, in moveit_setup::core::StartScreenWidget::loadNewFiles()
[moveit_setup_assistant-1] #10   Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b7135278, in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
[moveit_setup_assistant-1] #9    Object "/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0", at 0x7b83b5b13a62, in g_main_context_iteration
[moveit_setup_assistant-1] #8    Object "/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0", at 0x7b83b5b73736, in 
[moveit_setup_assistant-1] #7    Object "/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0", at 0x7b83b5b145c4, in 
[moveit_setup_assistant-1] #6    Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b7135c0e, in 
[moveit_setup_assistant-1] #5    Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b70db94a, in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
[moveit_setup_assistant-1] #4    Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b70d8117, in QCoreApplication::notifyInternal2(QObject*, QEvent*)
[moveit_setup_assistant-1] #3    Object "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.13", at 0x7b83b7d6bd44, in QApplicationPrivate::notify_helper(QObject*, QEvent*)
[moveit_setup_assistant-1] #2    Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b7106342, in QObject::event(QEvent*)
[moveit_setup_assistant-1] #1    Object "/opt/ros/jazzy/lib/librviz_common.so", at 0x7b83b88e5c00, in rviz_common::properties::PropertyTreeModel::propertyHiddenChanged(rviz_common::properties::Property const*)
[moveit_setup_assistant-1] #0    Object "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.13", at 0x7b83b711267c, in 
[moveit_setup_assistant-1] Segmentation fault (Address not mapped to object [0x9])
[ERROR] [moveit_setup_assistant-1]: process has died [pid 12797, exit code -11, cmd '/opt/ros/jazzy/lib/moveit_setup_assistant/moveit_setup_assistant --ros-args'].
brian@HP-laptop:~/master_ros2_ws$

**Comment by AimanHaidar** [comment]
@threent2 
I have faced this problem before. I found the solution in one of the issues and was due to version incompatibility of rviz2 with moveit. I downgraded rviz2 and worked well.
I don't know why developers not check integration before upload updates!

**Comment by detectedstealth** [comment]
Facing the same issue going through the book was smooth up until the moveit chapter.

**Comment by AimanHaidar** [comment]
@detectedstealth 
it solved by clone the rviz2 from source then checkout 14.1.7 then build as description in github repo of rviz2 and use it instead of the installed by apt

**Comment by threent2** [comment]
> [@threent2](https://github.com/threent2) I have faced this problem before. I found the solution in one of the issues and was due to version incompatibility of rviz2 with moveit. I downgraded rviz2 and worked well. I don't know why developers not check integration before upload updates!

I have installed 14.1.6 (already built) from the Ubuntu libraries but I still get the problem.

**Comment by AimanHaidar** [comment]
@threent2 
did you removed the original one and make sure to source the new build

**Comment by threent2** [comment]
> [@threent2](https://github.com/threent2) did you removed the original one and make sure to source the new build

I installed from the Ubuntu / Ros Jazzy libraries and so did not need to build. Using apt I can see that my installed version is 14.1.6

**Comment by AimanHaidar** [comment]
@threent2 

I don't know why this happen with you.
### my setup:

- latest moveit build from source (the main branch )
- rviz2 14.1.7

**Comment by detectedstealth** [comment]
@AimanHaidar > 14.1.7

How did you install this version? When I checkout the branch and try to follow the instructions:

colcon build --merge-install

And keep getting the following error:
```
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findament_cmake_vendor_package.cmake" in
  CMAKE_MODULE_PATH this project has asked CMake to find a package
  configuration file provided by "ament_cmake_vendor_package", but CMake did
  not find one.

  Could not find a package configuration file provided by
  "ament_cmake_vendor_package" with any of the following names:

    ament_cmake_vendor_packageConfig.cmake
    ament_cmake_vendor_package-config.cmake

  Add the installation prefix of "ament_cmake_vendor_package" to
  CMAKE_PREFIX_PATH or set "ament_cmake_vendor_package_DIR" to a directory
  containing one of the above files.  If "ament_cmake_vendor_package"
  provides a separate development package or SDK, be sure it has been
  installed.```

**Comment by AimanHaidar** [comment]
@detectedstealth 


I think it will download some packages while build so you should connect to internet and don't forget to source your ros2 workspace.

or try:

```bash
sudo apt install ros-jazzy-ament-cmake-vendor-package
```

or try the solution here:
[link](https://robotics.stackexchange.com/questions/111575/ament-cmake-vendor-package-does-it-exist)

**Comment by detectedstealth** [comment]
@AimanHaidar I was able too get it built from source and checking out the tag your referenced. Running the code from the next part of the book (Testing MoveIt 2 using Rviz2) while it loads the arm there are lots of errors in the console. This is the first chapter where I'm finding it confusing to follow. :)

**Comment by AimanHaidar** [comment]
@detectedstealth 

What are these errors?

moveit2 is a hell of errors. :)

**Comment by detectedstealth** [comment]
@AimanHaidar well for example if I remove all my build/install/log and only build panda_description it will load correctly. 

However if I build rviz2 + moveit2 from source code as well as the other packages from the chapter and try to run panda_description I get these kinds of errors and the robot arm doesn't show up.
```
[gazebo-5] [Err] [SystemPaths.cc:425] Unable to find file with URI [model://panda_description/meshes/visual/link1.dae]
[gazebo-5] [Err] [SystemPaths.cc:525] Could not resolve file [model://panda_description/meshes/visual/link1.dae]
[gazebo-5] [Err] [MeshManager.cc:211] Unable to find file[model://panda_description/meshes/visual/link1.dae]
[gazebo-5] [Wrn] [Util.cc:859] Failed to load mesh from [model://panda_description/meshes/visual/link1.dae].
[gazebo-5] [Err] [SceneManager.cc:426] Failed to load geometry for visual: link1_visual
[gazebo-5] [Err] [SystemPaths.cc:425] Unable to find file with URI [model://panda_description/meshes/visual/link2.dae]
[gazebo-5] [Err] [SystemPaths.cc:525] Could not resolve file [model://panda_description/meshes/visual/link2.dae]
[gazebo-5] [Err] [MeshManager.cc:211] Unable to find file[model://panda_description/meshes/visual/link2.dae]
[gazebo-5] [Wrn] [Util.cc:859] Failed to load mesh from [model://panda_description/meshes/visual/link2.dae].```

That's when running `ros2 launch panda_description panda_gazebo.launch.py`

**Comment by AimanHaidar** [comment]
@detectedstealth 

Oh, I remember I got error like this. the CADs seemed not loaded using the panda description from book's examples then I replaced the whole package with one in the moveit_resources workspace.

**Comment by detectedstealth** [comment]
@AimanHaidar yeah this chapter really should have been rewritten so many issues. I have the panda_description situation resolved I think but getting a new set of issues :D 

```
ros2 launch panda_moveit_control joint_space_planning.launch.py

[INFO] [launch]: All log files can be found below /home/bruceubuntu/.ros/log/2025-10-22-10-15-43-185225-bruceubuntu-Legion-Pro-7-16IAX10H-60357
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [joint_space_planning-1]: process started with pid [60360]
[joint_space_planning-1] [INFO] [1761153343.391501043] [moveit_301153243.moveit.ros.rdf_loader]: Loaded robot model in 0 seconds
[joint_space_planning-1] [INFO] [1761153343.391871262] [moveit_301153243.moveit.core.robot_model]: Loading robot model 'panda'...
[joint_space_planning-1] [INFO] [1761153343.396722917] [moveit_301153243.moveit.kinematics.kdl_kinematics_plugin]: Joint weights for group 'arm': 1 1 1 1 1 1 1
[joint_space_planning-1] [INFO] [1761153344.012931664] [moveit_301153243.moveit.ros.move_group_interface]: Ready to take commands for planning group arm.
[joint_space_planning-1] [INFO] [1761153344.012988897] [moveit_301153243.moveit.ros.move_group_interface]: MoveGroup action client/server ready
[joint_space_planning-1] [INFO] [1761153344.014009745] [moveit_301153243.moveit.ros.move_group_interface]: Planning request accepted
[joint_space_planning-1] [INFO] [1761153344.045636627] [moveit_301153243.moveit.ros.move_group_interface]: Planning request complete!
[joint_space_planning-1] [INFO] [1761153344.046158131] [moveit_301153243.moveit.ros.move_group_interface]: time taken to generate plan: 0.0176085 seconds
[joint_space_planning-1] [INFO] [1761153344.046511252] [moveit_301153243.moveit.ros.move_group_interface]: Plan and Execute request accepted
[joint_space_planning-1] [INFO] [1761153344.076088909] [moveit_301153243.moveit.ros.move_group_interface]: Plan and Execute request aborted
[joint_space_planning-1] [ERROR] [1761153344.076258732] [moveit_301153243.moveit.ros.move_group_interface]: MoveGroupInterface::move() failed or timeout reached
[joint_space_planning-1] [INFO] [1761153347.076402336] [moveit_301153243.moveit.ros.move_group_interface]: MoveGroup action client/server ready
[joint_space_planning-1] [INFO] [1761153347.076881747] [moveit_301153243.moveit.ros.move_group_interface]: Planning request accepted
[joint_space_planning-1] [INFO] [1761153347.094816851] [moveit_301153243.moveit.ros.move_group_interface]: Planning request complete!
[joint_space_planning-1] [INFO] [1761153347.095677721] [moveit_301153243.moveit.ros.move_group_interface]: time taken to generate plan: 0.0160742 seconds
[joint_space_planning-1] [INFO] [1761153347.096063241] [moveit_301153243.moveit.ros.move_group_interface]: Plan and Execute request accepted
[joint_space_planning-1] [INFO] [1761153347.125864535] [moveit_301153243.moveit.ros.move_group_interface]: Plan and Execute request aborted
[joint_space_planning-1] [ERROR] [1761153347.126777402] [moveit_301153243.moveit.ros.move_group_interface]: MoveGroupInterface::move() failed or timeout reached
```

```
ros2 launch panda_moveit_config move_group.launch.py

[move_group-1] [WARN] [1761153160.569776783] []: Invalid frame ID "link4" passed to canTransform argument source_frame - frame does not exist
[move_group-1] [ERROR] [1761153161.075624958] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 3
[move_group-1] [ERROR] [1761153161.075695907] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 6
[move_group-1] [ERROR] [1761153161.075701414] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 4
[move_group-1] [ERROR] [1761153161.075707783] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 9
[move_group-1] [ERROR] [1761153161.075711365] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 10
[move_group-1] [ERROR] [1761153161.075715269] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 7
[move_group-1] [ERROR] [1761153161.075718929] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 8
[move_group-1] [ERROR] [1761153161.075722755] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 5
[move_group-1] [ERROR] [1761153161.075726405] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 11
[move_group-1] [ERROR] [1761153161.075729973] [move_group.moveit.moveit.ros.shape_mask]: Missing transform for shape mesh with handle 12
...
[move_group-1] [INFO] [1761153347.115223020] [move_group]: Calling PlanningResponseAdapter 'DisplayMotionPath'
[move_group-1] [WARN] [1761153347.115247635] [move_group.moveit.moveit.ros.planning_pipeline]: The planner plugin did not fill out the 'planner_id' field of the MotionPlanResponse. Setting it to the planner ID name of the MotionPlanRequest assuming that the planner plugin does warn you if it does not use the requested planner.
[move_group-1] [INFO] [1761153347.115333519] [move_group.moveit.moveit.plugins.simple_controller_manager]: Returned 1 controllers in list
[move_group-1] [INFO] [1761153347.115370829] [move_group.moveit.moveit.plugins.simple_controller_manager]: Returned 1 controllers in list
[move_group-1] [INFO] [1761153347.115395831] [move_group.moveit.moveit.ros.trajectory_execution_manager]: Validating trajectory with allowed_start_tolerance 0.01
[move_group-1] [INFO] [1761153347.115497660] [move_group.moveit.moveit.ros.trajectory_execution_manager]: Starting trajectory execution ...
[move_group-1] [INFO] [1761153347.115548833] [move_group.moveit.moveit.plugins.simple_controller_manager]: Returned 1 controllers in list
[move_group-1] [INFO] [1761153347.115567008] [move_group.moveit.moveit.plugins.simple_controller_manager]: Returned 1 controllers in list
[move_group-1] [ERROR] [1761153347.115623916] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Action client not connected to action server: arm_controller/follow_joint_trajectory
[move_group-1] [ERROR] [1761153347.115632069] [move_group.moveit.moveit.ros.trajectory_execution_manager]: Failed to send trajectory part 1 of 1 to controller arm_controller
[move_group-1] [INFO] [1761153347.115638068] [move_group.moveit.moveit.ros.trajectory_execution_manager]: Completed trajectory execution with status ABORTED ...
[move_group-1] [INFO] [1761153347.125574251] [move_group.moveit.moveit.ros.move_group.move_action]: CONTROL_FAILED
```

```
ros2 launch panda_description panda_gazebo.launch.py

[gazebo-5] libEGL warning: egl: failed to create dri2 screen
[ros2-2] Traceback (most recent call last):
[ros2-2]   File "/opt/ros/jazzy/bin/ros2", line 33, in <module>
[ros2-2]     sys.exit(load_entry_point('ros2cli==0.32.6', 'console_scripts', 'ros2')())
[ros2-2]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-2]   File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2cli/cli.py", line 91, in main
[ros2-2]     rc = extension.main(parser=parser, args=args)
[ros2-2]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-2]   File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2controlcli/command/control.py", line 37, in main
[ros2-2]     return extension.main(args=args)
[ros2-2]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-2]   File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2controlcli/verb/load_controller.py", line 56, in main
[ros2-2]     controllers = list_controllers(node, args.controller_manager, 20.0).controller
[ros2-2]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-2]   File "/opt/ros/jazzy/lib/python3.12/site-packages/controller_manager/controller_manager_services.py", line 172, in list_controllers
[ros2-2]     return service_caller(
[ros2-2]            ^^^^^^^^^^^^^^^
[ros2-2]   File "/opt/ros/jazzy/lib/python3.12/site-packages/controller_manager/controller_manager_services.py", line 132, in service_caller
[ros2-2]     raise ServiceNotFoundError(
[ros2-2] controller_manager.controller_manager_services.ServiceNotFoundError: Could not contact service /controller_manager/list_controllers
[ros2-1] Traceback (most recent call last):
[ros2-1]   File "/opt/ros/jazzy/bin/ros2", line 33, in <module>
[ros2-1]     sys.exit(load_entry_point('ros2cli==0.32.6', 'console_scripts', 'ros2')())
[ros2-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-1]   File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2cli/cli.py", line 91, in main
[ros2-1]     rc = extension.main(parser=parser, args=args)
[ros2-1]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-1]   File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2controlcli/command/control.py", line 37, in main
[ros2-1]     return extension.main(args=args)
[ros2-1]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-1]   File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2controlcli/verb/load_controller.py", line 56, in main
[ros2-1]     controllers = list_controllers(node, args.controller_manager, 20.0).controller
[ros2-1]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ros2-1]   File "/opt/ros/jazzy/lib/python3.12/site-packages/controller_manager/controller_manager_services.py", line 172, in list_controllers
[ros2-1]     return service_caller(
[ros2-1]            ^^^^^^^^^^^^^^^
[ros2-1]   File "/opt/ros/jazzy/lib/python3.12/site-packages/controller_manager/controller_manager_services.py", line 132, in service_caller
[ros2-1]     raise ServiceNotFoundError(
[ros2-1] controller_manager.controller_manager_services.ServiceNotFoundError: Could not contact service /controller_manager/list_controllers
[ERROR] [ros2-2]: process has died [pid 59555, exit code 1, cmd 'ros2 control load_controller --set-state active arm_controller'].
[ERROR] [ros2-1]: process has died [pid 59554, exit code 1, cmd 'ros2 control load_controller --set-state active joint_state_broadcaster'].```

**Comment by AimanHaidar** [comment]
@detectedstealth 

I think you better rewrite your own example packages

or get into this hell, you will learn something new 😉

**Comment by runtimerobotics** [comment]
@jocacace can you please support this issue? I think they have been trying to solve this for a long time.

**Comment by runtimerobotics** [comment]
@detectedstealth, I will also look into this issue tomorrow. I think there are many bugs in MoveIt2. Seems like it each updation, new bugs are getting introduced. Let's @jocacace check the issue, because he written this chapter and better understanding of the same. If not, I will do the support.

**Comment by runtimerobotics** [comment]
@detectedstealth  @AimanHaidar At first sight. it seems like MoveIt2 bug, i will reproduce the same in my machine and check again. Please mention what is the exact Ubuntu version you guys using, and the computer spec if possible.

Seems like MoveIt2 open source team putting more effort to MoveIt pro which is a paid version. that may be reason we see more bugs.

**Comment by AimanHaidar** [comment]
@runtimerobotics  yes, that's true 
the bugs are due to update without checking
when I used moveit2 and rviz2 installed with "apt" I got these errors but then I degraded rviz2 which solved the problem of setup assistant but got other problems in not finding tfs from world to some links, I tried the panda_description in moveit_resources and it worked.

**Comment by runtimerobotics** [comment]
@runtimerobotics Yes, unfortunately, this is the situation with MoveIt2. There are some other bugs as well. If you check [MoveIt2 ](https://github.com/moveit/moveit2/issues) github, you can find about 233 open issues, which means open source version development is slow, it seems.

**Comment by detectedstealth** [comment]
@runtimerobotics I'm on Ubuntu 24.04, Nvidia RTX 5070TI, moveit2 looks like I built from main I'll try again from the jazzy branch, and rviz2 I built from the tag rviz-14.1.7. 

This is my second book on ROS2 related stuff I went through the ROS2 from Scratch first, trying to dive deep into this for Isaac Sim tasks.

**Comment by runtimerobotics** [comment]
@detectedstealth  I will try to test the same in docker tomorrow, let's see how it goes.

**Comment by detectedstealth** [comment]
FYI I was able to go through all of the tutorials on https://moveit.picknik.ai/main/doc/tutorials/tutorials.html without issues on my system. So its either the package provided or how its using a conflicting package name?

**Comment by detectedstealth** [comment]
Ok found a work around that is allowing me to use the examples in the chapter. 

Create a separate workspace for moveit2 (ws_moveit2) I'm using the one from the tutorial link setup above. Create another workspace for the chapter content (ws_mc9).

To start panda_gazebo in a terminal run (only terminal where ws_moveit2 is NOT sourced):

```
source /opt/ros/jazzy/setup.bash
source ~/ws_mc9/install/setup.bash
ros2 launch panda_description panda_gazebo.launch.py
```

Now for all the following commands in new terminals run:

```
source /opt/ros/jazzy/setup.bash
source ~/ws_moveit2/install/setup.bash
source ~/ws_mc9/install/setup.bash
ros2 launch panda_moveit_config move_group.launch.py
```

```
source /opt/ros/jazzy/setup.bash
source ~/ws_moveit2/install/setup.bash
source ~/ws_mc9/install/setup.bash
ros2 param set move_group use_sim_time true
```

```
source /opt/ros/jazzy/setup.bash
source ~/ws_moveit2/install/setup.bash
source ~/ws_mc9/install/setup.bash
ros2 launch panda_moveit_control joint_space_planning.launch.py
```

Found I am unable to source the ws_moveit2 to run the gazebo command because it gives errors it can't find the model paths.

The next example ros2 launch panda_moveit_control cartesian_space_planning.launch.py doesn't work either lots of errors about link7 not having any relation to the world.  Think I'll have to learn moveit from another resource and continue other chapters of the book.
